apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: busybox-deployment
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: busybox
     image: docker.artifactory/busybox:1.0
   ports:
   - containerPort: 8080
   imagePullSecrets:
   - name: regsecret
   livenessProbe:
    httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
          - name: X-Custom-Header
            value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3



