apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: busybox-deployment
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: busybox
     image: docker.artifactory/busybox:1.0
     livenessProbe:
       exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
   ports:
   - containerPort: 8080
   imagePullSecrets:
   - name: regsecret
   



