apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: helloworld-deployment
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: helloworld
     image: nlhartsaas-docker.jfrog.io/javasample/latest
   ports:
   - containerPort: 8080
   imagePullSecrets:
   - name: regsecret