apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        component: nginx
  spec:
    containers:
      - name: nginx
        image: jenkinspluginacr.azurecr.io/samples/nginx:latest
    imagePullSecrets:
      - name: regsecret


