apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: nginx
     image: docker.artifactory/samples/nginx:$BUILD_NUMBER.0
   ports:
   - containerPort: 8080
   imagePullSecrets:
   - name: regsecret



