apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: nginx
     image: docker.artifactory/hello-world:1.0
   imagePullSecrets:
   - name: regsecret


